---
# disable ipv6
- name: Disable ipv6 net.ipv6.conf.all.disable_ipv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/90-disable-ipv6.conf
    reload: yes

- name: Disable ipv6 net.ipv6.conf.default.disable_ipv6
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/90-disable-ipv6.conf
    reload: yes

- name: Disable ipv6 net.ipv6.conf.lo.disable_ipv6
  sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/90-disable-ipv6.conf
    reload: yes
