---
- name: Install nftables
  ansible.builtin.apt:
    name: unbound
    state: latest
    update_cache: yes

- name: Install nftables.conf
  copy:
    src: files/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0640'
  notify:
    - Restart nftables

- name: Install and enable nftables service
  systemd:
    name: nftables.service
    enabled: yes
    state: started
